// Garde-robe : chaque costume a ses couleurs, un bonus et (parfois) une condition de déblocage.
// Les 4 premiers sont liés aux styles de combat et toujours disponibles.

export const SUITS = {
  classique: {
    name: 'Classique',
    main: '#c8161d',
    second: '#1c3c9c',
    lines: '#2a0508',
    emblem: '#0c0c0c',
    eyes: '#ffffff',
    limb2: '#1c3c9c',
    bonus: {},
    bonusText: 'Équilibré : le costume de toujours.',
  },
  acrobate: {
    name: 'Symbiote',
    main: '#141418',
    second: '#1e1e24',
    lines: '#3c3c46',
    emblem: '#f2f2f2',
    eyes: '#ffffff',
    limb2: '#141418',
    emblemScale: 1.25,
    bonus: { focusMul: 1.15 },
    bonusText: 'Concentration +15 %',
  },
  brute: {
    name: 'Iron Spider',
    main: '#b0141b',
    second: '#d4a22a',
    lines: '#4a0a0a',
    emblem: '#e8b83a',
    eyes: '#ffffff',
    limb2: '#d4a22a',
    metal: true,
    bonus: { dmgTakenMul: 0.9 },
    bonusText: 'Dégâts reçus -10 %',
  },
  tisseur: {
    name: 'Spider 2099',
    main: '#18286e',
    second: '#0b0b16',
    lines: '#3551b5',
    emblem: '#e0222a',
    eyes: '#ff3030',
    limb2: '#0b0b16',
    bonus: { webBonus: 1 },
    bonusText: 'Chaque tir de toile entoile davantage',
  },
  film: {
    name: 'Film 2002',
    main: '#b3121c',
    second: '#1a3688',
    lines: '#120303',
    emblem: '#0a0a0a',
    eyes: '#eef2ff',
    limb2: '#1a3688',
    lineWidth: 2.6,
    panel: 0.09,
    emblemScale: 1.15,
    bonus: { regenMul: 1.6 },
    bonusText: 'Régénération +60 %',
    unlock: { missions: 2 },
    unlockText: 'Termine 2 missions de l’histoire',
  },
  scarlet: {
    name: 'Scarlet Spider',
    main: '#a8141a',
    second: '#2c55c9',
    lines: '#4a0000',
    emblem: '#2c55c9',
    eyes: '#ffffff',
    limb2: '#a8141a',
    panel: 0.2,
    emblemScale: 1.3,
    bonus: { dmgMul: 1.12 },
    bonusText: 'Dégâts +12 %',
    unlock: { bags: 5 },
    unlockText: 'Trouve 5 sacs à dos',
  },
  miles: {
    name: 'Miles',
    main: '#111114',
    second: '#111114',
    lines: '#b3121c',
    emblem: '#d4141c',
    eyes: '#ffffff',
    limb2: '#111114',
    emblemScale: 1.2,
    bonus: { gadgetCdMul: 0.7 },
    bonusText: 'Recharge des gadgets -30 %',
    unlock: { missions: 5 },
    unlockText: 'Termine 5 missions de l’histoire',
  },
  noir: {
    name: 'Noir',
    main: '#1c1c1e',
    second: '#29292c',
    lines: '#3a3a3f',
    emblem: '#4a4a4f',
    eyes: '#9aa4b0',
    limb2: '#29292c',
    bonus: { perfectWindow: 0.2 },
    bonusText: 'Esquives parfaites bien plus faciles',
    unlock: { crimes: 5 },
    unlockText: 'Arrête 5 crimes',
  },
  negatif: {
    name: 'Négatif',
    main: '#ececec',
    second: '#101010',
    lines: '#101010',
    emblem: '#101010',
    eyes: '#1a1a1a',
    limb2: '#101010',
    bonus: { swingMul: 1.1 },
    bonusText: 'Balancement +10 % plus rapide',
    unlock: { level: 6 },
    unlockText: 'Atteins le niveau 6',
  },
  dore: {
    name: 'Doré',
    main: '#caa02a',
    second: '#6e4f08',
    lines: '#5a3f05',
    emblem: '#141414',
    eyes: '#ffffff',
    limb2: '#6e4f08',
    metal: true,
    bonus: { xpMul: 1.25, dmgMul: 1.1 },
    bonusText: 'XP +25 % et dégâts +10 %',
    unlock: { missions: 9 },
    unlockText: 'Termine toute l’histoire',
  },
};

export const SUIT_ORDER = Object.keys(SUITS);

export function suitUnlocked(key, save) {
  const u = SUITS[key] && SUITS[key].unlock;
  if (!u) return true;
  if (u.missions && save.completed.length < u.missions) return false;
  if (u.bags && save.bags.length < u.bags) return false;
  if (u.crimes && (save.crimes || 0) < u.crimes) return false;
  if (u.level && save.level < u.level) return false;
  return true;
}
